CREATE TABLE ROLES
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  DEVELOPER BOOLEAN,
  PRODUCT_OWNER BOOLEAN,
  SCRUM_MASTER BOOLEAN
);
CREATE TABLE USER
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  FORENAME VARCHAR(255) NOT NULL,
  SURNAME VARCHAR(255) NOT NULL,
  ROLES_ID BIGINT,
  FOREIGN KEY (ROLES_ID) REFERENCES ROLES (ID),
  FOREIGN KEY (ROLES_ID) REFERENCES ROLES (ID)
);
CREATE TABLE ACCOUNT
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  USER_ID BIGINT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);
CREATE TABLE PROJECT
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  MANAGER_ID BIGINT NOT NULL,
  PRODUCT_OWNER_ID BIGINT,
  FOREIGN KEY (MANAGER_ID) REFERENCES USER (ID),
  FOREIGN KEY (PRODUCT_OWNER_ID) REFERENCES USER (ID)
);
CREATE TABLE PROJECT_USER
(
  PROJECT_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  SCRUM_MASTER BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);
CREATE TABLE USER_STORY
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ASSIGNED BOOLEAN,
  DESCRIPTION VARCHAR(255) NOT NULL,
  INDEX INTEGER,
  MARKET_VALUE INTEGER,
  NAME VARCHAR(255) NOT NULL,
  POINTS INTEGER,
  PROJECT_ID BIGINT NOT NULL,
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID)
);