INSERT INTO ROLES (DEVELOPER, SCRUM_MASTER, PRODUCT_OWNER) VALUES (true, true, true);
INSERT INTO ROLES (DEVELOPER, SCRUM_MASTER, PRODUCT_OWNER) VALUES (true, false, false);
INSERT INTO ROLES (DEVELOPER, SCRUM_MASTER, PRODUCT_OWNER) VALUES (true, true, false);
INSERT INTO ROLES (DEVELOPER, SCRUM_MASTER, PRODUCT_OWNER) VALUES (false, false, true);

INSERT INTO USER (FORENAME, SURNAME, EMAIL, ROLES_ID) VALUES ('Daenerys', 'Targaryen', 'dany.targaryen@got.wes', 1);
INSERT INTO USER (FORENAME, SURNAME, EMAIL, ROLES_ID) VALUES ('Jon', 'Snow', 'jon.snow@got.wes', 2);
INSERT INTO USER (FORENAME, SURNAME, EMAIL, ROLES_ID) VALUES ('Tyrion', 'Lannister', 'tyrion.lannister@got.wes', 3);
INSERT INTO USER (FORENAME, SURNAME, EMAIL, ROLES_ID) VALUES ('Eddard', 'Stark', 'ned.stark@got.wes', 4);

INSERT INTO ACCOUNT (USERNAME, PASSWORD, USER_ID) VALUES ('dany.targaryen', 'drakaris', 1);
INSERT INTO ACCOUNT (USERNAME, PASSWORD, USER_ID) VALUES ('jon.snow', 'iknownothing', 2);
INSERT INTO ACCOUNT (USERNAME, PASSWORD, USER_ID) VALUES ('tyrion.lannister', 'idrinkandiknowthings', 3);
INSERT INTO ACCOUNT (USERNAME, PASSWORD, USER_ID) VALUES ('ned.stark', 'winteriscoming', 4);