INSERT INTO ROLES(DEVELOPER, SCRUM_MASTER, PRODUCT_OWNER) VALUES(true, true, true);
INSERT INTO USER (FORENAME, SURNAME, EMAIL,ROLES_ID) VALUES ('Russel', 'Kane', 'r.kane@example.com',1);
INSERT INTO ACCOUNT (USER_ID, USERNAME, PASSWORD) VALUES (1, 'russell.kane', 'Intense123');
